spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        context:
          annotation: TRACE
        web: DEBUG
        nodeValue: INFO