CREATE TABLE PRODUCTS
(
    PRODUCT_ID   BINARY(16) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(20) UNIQUE NOT NULL,
    CATEGORY     VARCHAR(50)        NOT NULL,
    PRICE        BIGINT             NOT NULL,
    DESCRIPTION  VARCHAR(512) DEFAULT NULL,
    CREATED_AT   DATETIME(6)        NOT NULL,
    UPDATED_AT   DATETIME(6)  DEFAULT NULL
)