package com.cnu.coffee.order;

public enum OrderStatus {

    PAYMENT_REQUESTED,
    PAYMENT_COMPLETED,
    ORDER_COMPLETED,
    READY_TO_SHIPPING,
    SHIPPING,
    READY_TO_DELIVERY,
    IN_DELIVERY,
    DELIVERY_COMPLETED,
    CANCELED,
    RETURN_REQUESTED,
    IN_TRANSIT,
    RETURN_COMPLETE,
    CHECK_STUFF,
    REFUND_PROCESSING,
    REFUND_COMPLETED;


}
