spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/java/Grids-Circles-Clone-APIServer
    driver-class-name: org.h2.Driver
    username: sa
    password:


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
#      data-locations: /data.sql
      platform: h2
      encoding: UTF-8
#      mode: never
      mode: always

